Hw11
MaxOrlov1997/HW2 pull request #4
Opened 2023-04-22 15:01 UTC by MaxOrlov1997

2023-05-01 16:49 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Task1.java
> +        boolean a = student.firstName.equals(aspirant.firstName);
нам нужно сравнить не имена, а объекты целиком, student.equals(...)

2023-05-01 16:50 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Task1.java
> +        int x = student.firstName.hashCode();
нам нужно сравнить хешкоды не имен, а объектов целиком, student.hashCode()

2023-05-01 16:51 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    String currentFuel = "Disel";
currentFuel должен быть числом, сколько в баке осталось)

2023-05-01 16:51 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String muving(){
rename to move()

2023-05-01 16:52 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public void refuil(double tanksizeNow){
rename to refuel

2023-05-01 16:52 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String res(){
rename to toString

2023-05-01 16:52 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Recovery.java
> +    void refuil(double tanksizeNow);
rename to refuel

2023-05-01 16:53 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String muving(){
метод не должен ничего возвращать

2023-05-01 16:54 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String muving(){
плюс что должно происходить в методе, в цикле уменьшать топливо пока не будет 0, на каждый шаг печатать едем или уже закончилось топливо

2023-05-01 16:55 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String statistics(){
нужно убрать действия из этого метода, только вывод статистики в консоль

2023-05-01 16:55 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String statistics(){
соответственно метод ничего не возвращает

2023-05-01 16:56 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public int putPassenger() {
опять же, переусложнение, на каждый вызов метода либо
1) пишет "посадка успешна, всего сидит N пасажиров"
2) посадка невозможна, машина полная

2023-05-01 16:57 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public int putPassenger() {
метод ничего не принимает и ничего не возвращает

2023-05-01 16:57 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public double submergeCargo(){
аналогично метод putPassenger в PassengerCar

2023-05-01 16:58 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public double submergeCargo(){
и нужен еще один отдельный метод, который выгружает груз,

2023-05-03 11:46 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +        System.out.println("Автомобиль может проехать " + stat + " км");
хорошо бы этот вывод перенести до цикла

2023-05-03 11:47 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Recovery.java
> +    void refuel(double tanksizeNow);
refuel не должен принимать параметр, он заправляет до полного

2023-05-03 11:49 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public void statistics() {
еще раз, метод ничего не должен делать, только показывать статистику, например величину бака и текущее значение

2023-05-03 11:50 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +        System.out.println("В бак зальют - " + currentFuel);
но заливают то не currentFuel, который в данном случае всегда будет равен полному баку, заливают tanksize-currentFuel

2023-05-03 11:51 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public void putPassenger() {
повторю, мы не спрашивает садить ли пасажиров и сколько, метод отвечает за посадку, вызвал 1 раз - посадил 1 пасажира, вызвал 3 - посадил 3 пасажира.
Любое взаимодействие с консолью вне классов машин, можно в том же Runner

2023-05-03 11:51 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public void toMove() {
без to, просто move

2023-05-03 11:52 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void submergeCargo() {
повторю, мы не спрашивает сколько груза садить и сколько есть. метод отвечает за погрузку, вызвал 1 раз - загрузил груз, вызвал 2 - груз не помещается, сначала нужно выгрузить
Любое взаимодействие с консолью вне классов машин, можно в том же Runner

2023-05-03 11:53 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +        double stat = (this.currentFuel / this.fuelConsumption * 2) * 100;
тут говорит проедет в 2 раза больше, чем обычная, порядок операций проверь

2023-05-03 11:53 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +            currentFuel = currentFuel - fuelConsumption;
а тут отнимается обычное кол-во топлива,, а не х2

2023-05-03 11:53 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void putPassengerTruck() {
в грузовике не нужна посадка пасажиров

2023-05-03 11:54 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void unloadingCar(double cargo) {
повторю, мы не спрашивает сколько груза выгружать. метод отвечает за выгрузку, вызвал 1 раз - выгрузил груз(если он был)(, вызвал 2 - груза нет, сначала нужно погрузить
Любое взаимодействие с консолью вне классов машин, можно в том же Runner

2023-05-04 20:41 UTC, Bibi4kovIgor requested changes
Виправи, пліз зазначкені зауваження

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw10/Student.java
> +        if (avaregeMark == 5.0) {
Краще не використовувати "магічні цифри". При необхідності використання числових (або інших) констант, слід їх реалізовувати за допомогою final-змінних. Наприклад: **final float AVERAGE_VALUE = 5.0**

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw10/Student.java
> +            return 100;
див. зауваження вище

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw10/Student.java
> +            return 80;
Див. зауваження вище

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Car.java
> +    String year = "2021";
Константи слід позначати в "SCREAMING_SNAKE_CASE" а також за допомогою модифікатора final

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Car.java
> +    double tankSize = 200;
Константи не слід розміщувати в одному файлі із реалізацією
Константи слід зберігати в спеціалізованих утилітарних інтерфейсах:
package utils;
public interface Constants {
  double CURRENT_FUEL = 60.0;
  ...
}

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Car.java
> +    public void move() {
Проектувати методи слід так, щоб вони повертали значення.
Операції, що передбачають введення/вивід слід виділяти в окремі методи 
Твій метод "move()",  слід розбити на делілька методів, що змінювали б поля: 
public double getVehicleRange() {return  (this.currentFuel / this.fuelConsumption) * 100}
public double getCurrentFuelState() {return   currentFuel - fuelConsumption;} 
...

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Car.java
> +        currentFuel = this.tankSize - this.currentFuel;
Тут краще повертати значення типу  boolean: 
isTankRefuel() {...}

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public void putPassenger(int passenger) {
Тут доречніше було б просто виконувати зміну кількості ппасажирів:
операції **System.out.println** прибрати

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void submergeCargo(int cargoIncar, int cargoOncar) {
Тут краще повертати boolean

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Truck.java
> +            System.out.println("Не возможно взять больше 1000, необходима разгрузка");
Замість того, щоб в методі виводити повідомлення, краще тут виконувати обчислення та повертати стан (завантажений або ні: true/false)

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void move() {
Аналогічне зауваження, як і до реалізації класу Car

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void unloadingCar(double cargoOut) {
Яка мета даного методу?

2023-05-04 20:41 UTC, Bibi4kovIgor commented on src/test/java/ua/orlov/hw10/TestStudentAspirant.java
> +        double num= 4.5;
Можна винести спільні значення (як константи) у секцію @BeforeAll

2023-05-04 21:17 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    String year = "2021";
побуду немного адвокатом, тут не константы предполагались, а изменяемые поля класса, но инициализацию лучше перенести в конструктор

2023-05-08 17:15 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +        for (int i = 0; currentFuel > 0; i++) {
переменная i нигде не используется, лучше заменить на while или do-while

2023-05-08 17:17 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +        System.out.println("Желаете заправить после поездки? Yes/No");
в третий раз, повторюсь, убери из методов взаимодействие с пользователем, доехали до конца, вывели сообщение и все, the end

2023-05-08 17:17 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Recovery.java
> +    boolean isTankRefuel();
метод refuel, возвращает void

2023-05-08 17:20 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public int putPassenger(int passenger) {
что делает этот метод?
явно не то что указано, должен садить 1(или нескольких, если уж сильно хочется использовать параметр), сравнить с текущим кол-вом пасажиров (кстати где оно?) и добавить если хватает мест, если нет - выдать ошибку

2023-05-08 17:20 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public boolean submergeCargo(int cargoIncar, int cargoOncar) {
упрости метод до погрузки атомарного большого ящика, который или есть или нет его

2023-05-08 17:21 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void unloadingCar(double cargoOut) {
аналогично загрузке

2023-05-08 17:21 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +        System.out.println("Желаете заправить после поездки? Yes/No");
аналогично реализации в Car

2023-05-09 16:04 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public int putPassenger(int passenger) {
Вы сперва разберитесь с преподавателем который заменял, он сказал только садить пассажиров, не спрашивать сколько было!!!

2023-05-14 21:18 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw10/Aspirant.java
> +String work = "Scientific work";
нужно сделать то же самое, что у студента, убрать отсюда инициализацию и сделать через конструктор

2023-05-14 21:18 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw10/Aspirant.java
> +    public void scientificWork() {
переименовать в getScientificWork() и возвращать строку, **НЕ** печатать в консоль

2023-05-14 21:19 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw10/Aspirant.java
> +    public double getScholarship(double avaregeMark) {
методу не нужно принимать параметр, данные уже есть в объекте this

2023-05-14 21:19 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw10/Student.java
> +    public double getScholarship(double avaregeMark) {
методу не нужно принимать параметр, данные уже есть в объекте this

2023-05-14 21:20 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +        Scanner scan = new Scanner(System.in);
ладно, объясню по-другому, просто удали строки 42-46, не нужно тут взаимодействие с вводом

2023-05-14 21:20 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public double getCurrentFuelState() {
можно сделать private

2023-05-14 21:21 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +    public void statistics() {
rename to printStatistics

2023-05-14 21:21 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +        System.out.println("В бак зальют - " + currentFuel);
не нужный вывод

2023-05-14 21:21 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Car.java
> +        currentFuel = this.tankSize - this.currentFuel;
почему taskSize - currentFuel? мы же полный бак хотим залить

2023-05-14 21:22 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public int putPassenger(int passenger) {
в конечном итоге проверяю я, поэтому ориентируйся на мои последние комментарии

2023-05-14 21:22 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Recovery.java
> +    void isTankRefuel();
rename to refuel

2023-05-14 21:23 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Task1.java
> +        System.out.println(a);
добавь к выводу описание что выводится, например student equals to aspirant: {result}

2023-05-14 21:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +        cargo = cargoIncar;
если груз есть (!=0) - вывод ошибки, если нет - заменить значение и оставить тот вывод, что сейчас есть

2023-05-14 21:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +        Scanner scan = new Scanner(System.in);
аналогично Car

2023-05-14 21:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public double getCurrentFuelState() {
private

2023-05-14 21:25 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public void unloadingCar(double cargoOut) {
не нужно ничего принимать, просто выгрузка
если груз был - выводит число, значение груза, которое было
текущее значение в поле заменить на 0
если груза нет - вывести что груза нет

2023-05-15 18:16 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw10/Student.java
> +    public double getScholarship(double avaregeMark) {
Я дз 10 уже сделал, после того как соединю ветки, будет дз10 которую ты уже принял

2023-05-15 18:16 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw10/Aspirant.java
> +    public double getScholarship(double avaregeMark) {
Я дз 10 уже сделал, после того как соединю ветки, будет дз10 которую ты уже принял

2023-05-15 18:16 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw10/Aspirant.java
> +    public void scientificWork() {
Я дз 10 уже сделал, после того как соединю ветки, будет дз10 которую ты уже принял

2023-05-15 18:17 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw10/Aspirant.java
> +String work = "Scientific work";
Я дз 10 уже сделал, после того как соединю ветки, будет дз10 которую ты уже принял

2023-05-15 18:59 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Task1.java
> +        System.out.println("student equals to aspirant: " + b);
aspirant equals to student?

2023-05-15 19:00 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
>          cargo = cargoIncar;
все, что после if помести в else блок

2023-05-15 19:00 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
> +        refuel();
заправлять тут не нужно

2023-05-15 19:00 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/Truck.java
>          System.out.println("Груз в машине " + cargo);
опять же, все что после If - помести в else блок

2023-05-15 19:01 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
>              System.out.println("Нет посадочных мест, автомобиль может вместить всего 3 пассажиров");
опять же, эта надпись будет выведена в любом случае

2023-05-15 19:01 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
>          for (; ; ) {
и цикл бесконечный, без выхода из него (цикл тут вообще не нужен)

2023-05-15 19:02 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    public void putPassenger(int passengerinCar, int newpassenger) {
первый параметр должен быть полем класса, сколько сидит пасажиров, второй не нужен, он всегда равен 1

2023-05-16 14:19 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +    int passengerinCar = 2;
отформатируй в соответствии с camelCase

2023-05-16 14:19 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +        if (passenger <= 3) {
последнее осталось, внутри if блока записать в passengerinCar новое значение, которое лежит в passenger

2023-05-17 18:44 UTC, ArtemKharin approved these changes
approved

2023-05-18 09:57 UTC, merged