Hw12
MaxOrlov1997/HW2 pull request #5
Opened 2023-04-27 15:13 UTC by MaxOrlov1997

2023-05-01 17:01 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/PhoneBook.java
> +        System.out.println(res);
res это optional, а нам нужно распечатать число, которое в нем лежит

2023-05-01 17:01 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/PhoneBook.java
> +                return Optional.of(Integer.valueOf("Номер есть"));
нужно найти индекс, а не "номер есть"

2023-05-01 17:03 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task2.java
> +
удаляй лишние пустые строки

2023-05-01 17:04 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task2.java
> +        try {
в main достаточно вызвать только f(), второй блок try-catch не нужен, метод g() и так вызывается внутри f()

2023-05-01 17:06 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task3.java
> +public class Task3 {
тут прям оооочень странно все, давай переделаем заново.

- есть 3 класса исключений, которые наследуются от Exception, а не от Task3
- в main нужно вызвать void метод, который не возвращает, а выбрасывает одно из трех исключений (рандомно)
- так же в main обработать все три типа исключений одним catch блоком

2023-05-03 11:57 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +public class Exceptions {
чуть больше похоже на правду, но снова повторюсь:?
тут прям оооочень странно все, давай переделаем заново.

есть 3 класса исключений, которые наследуются от Exception, а не от Exceptions 
в main нужно вызвать void метод, который не возвращает, а выбрасывает одно из трех исключений (рандомно)
так же в main обработать все три типа исключений одним catch блоком

2023-05-03 11:57 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/PhoneBook.java
> +        System.out.println(res);
выходит что если res пустой, то мы все равно выводим его в консоль. А по идее должны вывести сообщение ,что номер не найден

2023-05-04 21:11 UTC, Bibi4kovIgor requested changes
Будь ласка, виправ помилки та прокоментуй методи, в яких я залишав коментарі щодо доцільності, або "???"

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw10/Aspirant.java
> +        if (avaregeMark == 5) {
Не слід застосовувати "магічні цифри". Якщо є потреба у значеннях, які не змінюються протягом застосування даного об'єкта, їх слід задавати через константи

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw10/Lambda.java
> +        Pow op = (number, pow) -> {
Якщо в лямбді використовується більше 1 операції, то дану логіку слід виділити в окремий метод і викликати його тут

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw10/Runner.java
> +    public static void main(String... args) {
Якщо ти використовуєш тести для перевірки роботи коду,  немає сенсу в main() робити те саме.
**public static void main(String[] args) {}** зазвичай містить лише 1 виклик основного коду програми (тобто, використовується, виключнео, як точка входу до виконання програми)

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw10/Student.java
> +   public String firstName = "Max";
Константні значення слід виділяти окремо, в інтерфейси (в окремому пакеті utils)

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String statistics(){
Цей метод дуже сходжий на toString()
Для здійснення обчислень, слід розвити даний метод на окремі методи під кожну операцію. В такому випадку, нові методи будуть повертати відповідні значення
Всі операції введення/виводу мають бути виділені у спеціальні методи

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Car.java
> +    public void refuil(double tanksizeNow){
аналогічне попередньому зауваженню, вказаному вище

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Car.java
> +    public String res(){
аналогічне попередньому зауваженню, вказаному вище

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/PassengerCar.java
> +            System.out.println("Нет посадочных мест, автомобиль может вместить всего 3 пассажиров");
Всі методи, що використовуються для введення/виводу мають бути розміщені у відповідних методах

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public double submergeCargo(){
Цей метод дуже сходжий на toString()
Для здійснення обчислень, слід розвити даний метод на окремі методи під кожну операцію.
В такому випадку, нові методи будуть повертати відповідні значення
Всі операції введення/виводу мають бути виділені у спеціальні методи

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw11/Truck.java
> +    public String muving(){
Дана реалізація, очевидно, однакова для всіх класів. 
Слід винести даний метод у батьківський, а потім його просто викликати для різних об'єктів

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +        } catch (IllegalAccessError a) {
Чосу саме таке виключення?

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/FirstExtend.java
> +    public static void firstExtend() throws IllegalAccessError {
Не до кінця зрозуміло доцільність даного виключення

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/LastExtend.java
> +    public static void lastExtend() throws IllegalAccessError {
Не до кінця зрозуміло доцільність даного виключення

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/SecondExtend.java
> +    public static void secondExtend() throws IllegalAccessError {
Не до кінця зрозуміло доцільність даного виключення

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/Task1.java
> +            System.out.println("Мы тут были");
?

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/Task2.java
> +            f();
???

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/Task2.java
> +            g();
???

2023-05-04 21:11 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw12/Task2.java
> +    private static void g() throws IllegalAccessError {
???

2023-05-04 21:23 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task1.java
> +            System.out.println("Мы тут были");
тут все согласно заданию)

2023-05-04 21:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task2.java
> +            f();
тут все согласно заданию, просто вызов метода с заранее определенным названием

2023-05-04 21:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task2.java
> +            g();
тут все согласно заданию, просто вызов метода с заранее определенным названием

2023-05-08 17:23 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +           rundom();
rename to throwRandomException

2023-05-08 17:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +            FirstExtend.firstExtend();
просто выброси throw new FirstExtend(), зачем вызывать метод, который выбрасывает исключение, да еще и не то, что нужно?

2023-05-08 17:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +            LastExtend.lastExtend();
см коммент выше

2023-05-08 17:24 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +            SecondExtend.secondExtend();
см коммент выше

2023-05-08 17:25 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/FirstExtend.java
> +    public static void firstExtend() throws IllegalArgumentException {
метод не нужен

2023-05-08 17:25 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/LastExtend.java
> +    public static void lastExtend() throws IllegalArgumentException {
метод не нужен

2023-05-08 17:25 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/SecondExtend.java
> +    public static void secondExtend() throws IllegalArgumentException {
метод не нужен

2023-05-08 17:26 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/SecondExtend.java
> +public class SecondExtend extends Exception {
переименуй так, чтобы название заканчивалось на exception

2023-05-08 17:26 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/PhoneBook.java
> +        System.out.println("Номер не найден");
форматирвоание

2023-05-14 21:26 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +        } catch (IllegalAccessError a) {
нужно отловить 3 разных типа исключений, а не одно, у тебя были три класса исключений, удалил зря

2023-05-14 21:27 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Exceptions.java
> +            throw new NumberFormatException("Тут один");
в каждом из случаев нужно выбросить разные исключения, разные классы исключений (которые ты создал)

2023-05-14 21:27 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task2.java
> +        throw new IllegalArgumentException(name);
замени в этом файле IllegalArgumentException на какое-то из проверяемых

2023-05-15 19:04 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw12/Task2.java
> +        throw new IllegalArgumentException(name);
разве runtimeexception это проверяемые?

2023-05-17 12:02 UTC, ArtemKharin approved these changes
approved

2023-05-17 18:35 UTC, merged