hw14
MaxOrlov1997/HW2 pull request #8
Opened 2023-05-04 17:54 UTC by MaxOrlov1997

2023-05-04 20:48 UTC, Bibi4kovIgor requested changes
Виправ, пліз, зауваження

2023-05-04 20:48 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw14/MySet.java
> +        System.out.println(Arrays.toString(generic));
Тут, замість System.out.println() повертати String:
**return Arrays.toString(generic);**
Сам **toString()** має бути викликаний в main

2023-05-04 20:48 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw14/MySet.java
> +    public <T> T[] add(T number) {
Чому метод add() повертає T[]?

2023-05-04 20:48 UTC, Bibi4kovIgor commented on src/main/java/ua/orlov/hw14/MySet.java
> +        mySet.toString();
Тут виклик методу toString() має бути (неявний):  System.out.println(mySet);

2023-05-04 21:15 UTC, ArtemKharin commented
@Bibi4kovIgor спасибо за ревью)

2023-05-04 21:19 UTC, Bibi4kovIgor commented
@ArtemKharin 
Похоже, студент неправильно заассайнил все пулл-реквесты)
Мой только по BigO)))

2023-05-04 21:22 UTC, Bibi4kovIgor commented
@ArtemKharin 
Стоп... Сорян... То я завтікал по запаре))

2023-05-08 17:27 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/MySetStat.java
> +public class MySetStat {
какое задание выполняет этот класс?

2023-05-08 17:28 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/MySetNoStat.java
> +public class MySetNoStat<T> {
какое задание выполняет этот класс?

2023-05-08 17:28 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/MySet.java
> +    public MySet(T[] generic) {
нужно указать размер массива через параметр конструктора и создать массив внутри конструктора

2023-05-08 17:29 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/MySet.java
> +    public T[] add(T number) {
- метод берет параметр чтобы добавить его в массив - это верно
- возвращает массив - неверно, ему не нужно ничего возвращать

2023-05-08 17:31 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/MySet.java
> +        T[] gener = Arrays.copyOf( generic, generic.length + 1);
для чего создавать новый массив? все что нужно сделать - проверить есть ли такой элемент в массиве и помещается ли он в текущий массив, если все ок - записать на первое свободное место

2023-05-08 17:32 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/MySet.java
> +        System.out.println("Длина - " + size);
никаких выводов в консоль быть в этом методе не должно

2023-05-08 17:33 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/MySet.java
> +        T[] gener = Arrays.copyOf( generic, generic.length + 1);
на реализацию похожую можешь посмотреть в моем репозитории в MyIntegerList
только там размер меняется, тут нет, и там не проверяется на дубли

2023-05-09 16:47 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw14/MySetStat.java
> +public class MySetStat {
сам для себя оставил, практиковался в методе со статиками

2023-05-09 16:49 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw14/MySetNoStat.java
> +public class MySetNoStat<T> {
task2

2023-05-09 17:29 UTC, MaxOrlov1997 commented on src/main/java/ua/orlov/hw14/MySet.java
> +    public MySet(T[] generic) {
Я НЕ ПОНИМАЮ КАК ЭТО СДЕЛАТЬ!!!!! Я В ТЕЛЕ ПИСАЛ ЧТО НЕ ЗНАЮ!!!

2023-05-17 12:04 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +public class Task2MySet<T> {
Реализовать класс-утилиту которая содержит два generic метода
(статический и не статический):
Метод 1: принимает любое значение и выводит ***{значение}***
Метод 2: принимает массив любого типа и выводит его содержание

2023-05-17 12:05 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +public class Task2MySet<T> {
то что представлено в файле не похоже на реализацию этого задания

2023-05-17 12:05 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +public class Task2MySet<T> {
даже если предположить, что где-то отдаленно похожи методы, то где выводы в консоль? зачем сохраняется какой-то list?

2023-05-18 18:55 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +    private static <T> void add(T nam) {
1) такого рода ультильные методы обычно делают public, для внешнего использования
2) имя метода add, что он и куда добавляет? нужно подумать как назвать иначе

2023-05-18 18:55 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +    private void addMas(T[] array) {
1) такого рода ультильные методы обычно делают public, для внешнего использования
2) имя метода addMas, он куда-то добавляет массив? нужно подумать как назвать иначе

2023-05-18 18:57 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +        task2MySet.addMas(new Object[]{2, "Name", 4.5});
давай или добавим другой пример или заменим на более типовый массив, где хранятся не Object, а, например, строки

2023-05-19 12:09 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +    public static <T> void addValueAnyType(T nam) {
мы не добавляем add, мы выводим в консоль, более подходящее дествие для названия -  print

2023-05-19 12:09 UTC, ArtemKharin commented on src/main/java/ua/orlov/hw14/Task2MySet.java
> +    public void addArrayAnyType(T[] array) {
мы не добавляем add, мы выводим в консоль, более подходящее дествие для названия -  print

2023-05-23 18:38 UTC, ArtemKharin approved these changes
approved

2023-05-24 13:11 UTC, merged